### ISSUE TITLE
Foolbox with Tensorflow 2.0

### ISSUE THREAD

**Issue by tkupek** [bethgelab/foolbox#411]
I am trying to use foolbox on a Keras Model with Tensorflow 2.0 but I'm getting this error:

`File "...\Python\Python36\lib\site-packages\foolbox\models\keras.py", line 54, in __init__
    label_input = K.placeholder(shape=(1,))
  File "...\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'`

Are there any plans of updating foolbox to work with Tensorflow 2.0?

**Comment by jonasrauber** [comment]
Try `TensorFlowEagerModel`

**Comment by tkupek** [comment]
@jonasrauber this did the trick.
Thanks alot for the hint!
